#Name of the project 
Project_name = Rock, paper, scissor game

target: main.c
	gcc main.c -o all.out

#output directory
BUILD=BUILD

#source code files
SRC=main.code

all:$(SRC)$(BUILD)

run:target
	./all.out

clean:
	rm all.out
	
